-- Copy and Paste this into your Supabase SQL Editor to initialize your tables!

-- ==========================================
-- 1. Create Doctors Table (IF NOT EXISTS)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.doctors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  specialty TEXT,
  role TEXT,
  experience TEXT,
  location TEXT,
  fee TEXT,
  satisfaction TEXT,
  stories TEXT,
  avatar TEXT,
  availability TEXT[], 
  gender TEXT
);

-- Insert Mock Doctor Data (Idempotent using ON CONFLICT)
INSERT INTO public.doctors (id, name, specialty, role, experience, location, fee, satisfaction, stories, avatar, availability, gender) VALUES
(1, 'Dr. Aryan Sharma', 'Cardiologist • MBBS, MD (Cardiology)', 'Senior Cardiologist & Heart Surgeon', '15 years experience overall', 'Fortis Memorial, Gurugram', '₹800', '98%', '450+', 'https://i.pravatar.cc/150?img=11', ARRAY['Available Today', 'Available Tomorrow', 'Next 3 Days'], 'Male'),
(2, 'Dr. Meera Iyer', 'Pediatrician • MBBS, DCH', 'Senior Pediatrician', '10 years experience overall', 'Max Super Speciality, Saket', '₹600', '96%', '210+', 'https://i.pravatar.cc/150?img=5', ARRAY['Available Tomorrow', 'Next 3 Days'], 'Female'),
(3, 'Dr. Vikram Reddy', 'Dermatologist • MD (Derm), DNB', 'Consultant Dermatologist', '22 years experience overall', 'Apollo Hospitals, Sarita Vihar', '₹1200', '99%', '890+', 'https://i.pravatar.cc/150?img=8', ARRAY['Available Today', 'Next 3 Days'], 'Male'),
(4, 'Dr. Sana Sheikh', 'Gynecologist • MBBS, MS (OBG)', 'Lead Gynecologist', '12 years experience overall', 'Cloudnine Hospital, Noida', '₹900', '95%', '340+', 'https://i.pravatar.cc/150?img=9', ARRAY['Available Today', 'Available Tomorrow'], 'Female'),
(5, 'Dr. Arjun Patel', 'Neurologist • MBBS, DM (Neurology)', 'Consultant Neurologist', '18 years experience overall', 'Medanta, Gurugram', '₹1500', '97%', '560+', 'https://i.pravatar.cc/150?img=12', ARRAY['Next 3 Days'], 'Male'),
(6, 'Dr. Kavita Singh', 'Dentist • BDS, MDS', 'Senior Dental Surgeon', '8 years experience overall', 'Clove Dental, South Ex', '₹400', '94%', '180+', 'https://i.pravatar.cc/150?img=10', ARRAY['Available Today', 'Available Tomorrow', 'Next 3 Days'], 'Female'),
(7, 'Dr. Rahul Verma', 'General Physician • MBBS, MD', 'Family Medicine Specialist', '25 years experience overall', 'BLK Super Speciality, Delhi', '₹700', '98%', '920+', 'https://i.pravatar.cc/150?img=14', ARRAY['Available Today', 'Next 3 Days'], 'Male')
ON CONFLICT (id) DO NOTHING;


-- ==========================================
-- 2. Create Bookings Table (IF NOT EXISTS)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doctor_id BIGINT REFERENCES public.doctors(id),
  doctor_name TEXT,
  day INT,
  slot TEXT,
  fee TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.doctors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;

-- Idempotent RLS Policies for Doctors & Bookings
DROP POLICY IF EXISTS "Allow public read access to doctors" ON public.doctors;
CREATE POLICY "Allow public read access to doctors" ON public.doctors FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert to bookings" ON public.bookings;
CREATE POLICY "Allow public insert to bookings" ON public.bookings FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read to bookings" ON public.bookings;
CREATE POLICY "Allow public read to bookings" ON public.bookings FOR SELECT USING (true);


-- ==========================================
-- 3. Create Medications Table (IF NOT EXISTS)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.medications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  dosage TEXT,
  indication TEXT,
  schedule TEXT,
  remaining TEXT,
  type TEXT,
  status TEXT,
  icon TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for Medications
ALTER TABLE public.medications ENABLE ROW LEVEL SECURITY;

-- Idempotent RLS Policies for Medications
DROP POLICY IF EXISTS "Allow public read access to medications" ON public.medications;
CREATE POLICY "Allow public read access to medications" ON public.medications FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert to medications" ON public.medications;
CREATE POLICY "Allow public insert to medications" ON public.medications FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update to medications" ON public.medications;
CREATE POLICY "Allow public update to medications" ON public.medications FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow public delete to medications" ON public.medications;
CREATE POLICY "Allow public delete to medications" ON public.medications FOR DELETE USING (true);

-- Insert Mock Medication Data (Idempotent using ON CONFLICT)
INSERT INTO public.medications (id, name, dosage, indication, schedule, remaining, type, status, icon) VALUES
(1, 'Lisinopril', '10mg', 'Hypertension Management', '8:00 AM Daily', '12 / 30', 'pills', 'Refill Now', 'pill'),
(2, 'Metformin', '500mg', 'Type 2 Diabetes Control', 'With Breakfast', '5 / 60', 'pills', 'Refill Urgent', 'pill_off'),
(3, 'Vitamin D3', '2000IU', 'Immune Support', '1x Weekly (Sun)', '24 / 24', 'caps', 'Refill Not Ready', 'medication_liquid')
ON CONFLICT (id) DO NOTHING;


-- ==========================================
-- 4. Create Profiles Table (IF NOT EXISTS)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.profiles (
  email TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  phone TEXT,
  dob DATE,
  gender TEXT,
  blood_type TEXT,
  height NUMERIC,
  weight NUMERIC,
  allergies TEXT,
  conditions TEXT,
  password TEXT, -- Plain text password for testing/mock-authentication purposes
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Alter Medications Table to support per-user schedules (Idempotent)
ALTER TABLE public.medications ADD COLUMN IF NOT EXISTS user_email TEXT;


-- ==========================================
-- 5. Create Symptom Chats Table (IF NOT EXISTS)
-- ==========================================
CREATE TABLE IF NOT EXISTS public.symptom_chats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_email TEXT NOT NULL,
  specialist_id TEXT NOT NULL,
  role TEXT NOT NULL, -- 'user' or 'ai'
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS for Profiles & Symptom Chats
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.symptom_chats ENABLE ROW LEVEL SECURITY;

-- Idempotent RLS Policies for Profiles
DROP POLICY IF EXISTS "Allow public read access to profiles" ON public.profiles;
CREATE POLICY "Allow public read access to profiles" ON public.profiles FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert to profiles" ON public.profiles;
CREATE POLICY "Allow public insert to profiles" ON public.profiles FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update to profiles" ON public.profiles;
CREATE POLICY "Allow public update to profiles" ON public.profiles FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow public delete to profiles" ON public.profiles;
CREATE POLICY "Allow public delete to profiles" ON public.profiles FOR DELETE USING (true);

-- Idempotent RLS Policies for Symptom Chats
DROP POLICY IF EXISTS "Allow public read access to symptom_chats" ON public.symptom_chats;
CREATE POLICY "Allow public read access to symptom_chats" ON public.symptom_chats FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert to symptom_chats" ON public.symptom_chats;
CREATE POLICY "Allow public insert to symptom_chats" ON public.symptom_chats FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update to symptom_chats" ON public.symptom_chats;
CREATE POLICY "Allow public update to symptom_chats" ON public.symptom_chats FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow public delete to symptom_chats" ON public.symptom_chats;
CREATE POLICY "Allow public delete to symptom_chats" ON public.symptom_chats FOR DELETE USING (true);
