import React, { useState, useRef } from 'react';
import AppLayout from '../components/AppLayout';
import { useAuth } from '../context/AuthContext';

/* ─── helpers ─── */
const formatDob = (dob) => {
    if (!dob) return 'Not provided';
    const d = new Date(dob);
    const age = Math.floor((Date.now() - d.getTime()) / (365.25 * 24 * 60 * 60 * 1000));
    return `${d.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })} (${age} yrs)`;
};
const formatGender = (g) => (!g ? 'Not provided' : g.charAt(0).toUpperCase() + g.slice(1).replace('-', ' '));
const getTags = (str) => (str?.trim() ? str.split(',').map((s) => s.trim()).filter(Boolean) : []);

/* ─── sub-component: InfoRow ─── */
const InfoRow = ({ label, value }) => (
    <div>
        <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-1">{label}</p>
        <p className="font-semibold text-sm text-slate-800 dark:text-slate-200">{value || 'Not provided'}</p>
    </div>
);

/* ─── sub-component: GoalBar ─── */
const GoalBar = ({ label, current, target, unit, pct, color }) => (
    <div>
        <div className="flex justify-between text-xs font-bold mb-1.5">
            <span className="text-slate-500">{label}</span>
            <span className={`text-${color}-600`}>{current} / {target} {unit}</span>
        </div>
        <div className="h-2 w-full bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden">
            <div className={`h-full bg-${color}-500 rounded-full transition-all duration-700`} style={{ width: `${pct}%` }} />
        </div>
    </div>
);

/* ─── main component ─── */
const PatientProfileRecords = () => {
    const { user, updateProfile } = useAuth();
    const [isEditing, setIsEditing]     = useState(false);
    const [organDonor, setOrganDonor]   = useState(false);
    const [saveSuccess, setSaveSuccess] = useState(false);
    const [photoSrc, setPhotoSrc]       = useState(user?.photoUrl || null);
    const photoInputRef = useRef(null);

    const initials = user?.name
        ? user.name.split(' ').map((n) => n[0]).join('').toUpperCase().slice(0, 2)
        : 'U';

    /* ── Save profile ── */
    const handleSubmit = async (e) => {
        e.preventDefault();
        const fd = new FormData(e.target);
        const fields = {
            name:      fd.get('name'),
            phone:     fd.get('phone'),
            gender:    fd.get('gender'),
            dob:       fd.get('dob'),
            bloodType: fd.get('bloodType'),
            height:    fd.get('height') ? Number(fd.get('height')) : '',
            weight:    fd.get('weight') ? Number(fd.get('weight')) : '',
            allergies: fd.get('allergies'),
            conditions: fd.get('conditions'),
        };
        await updateProfile(user?.email, fields);
        setIsEditing(false);
        setSaveSuccess(true);
        setTimeout(() => setSaveSuccess(false), 4000);
    };

    /* ── Download health report ── */
    const handleDownload = () => {
        const lines = [
            '╔════════════════════════════════════════════════╗',
            '║            SWASTHYA MITRA — HEALTH REPORT      ║',
            '╚════════════════════════════════════════════════╝',
            '',
            `Generated : ${new Date().toLocaleString()}`,
            '',
            '── PERSONAL INFORMATION ─────────────────────────',
            `Name       : ${user?.name || '—'}`,
            `Email      : ${user?.email || '—'}`,
            `Phone      : ${user?.phone || '—'}`,
            `Gender     : ${formatGender(user?.gender)}`,
            `Date of Birth : ${formatDob(user?.dob)}`,
            '',
            '── MEDICAL ID ───────────────────────────────────',
            `Blood Type : ${user?.bloodType || '—'}`,
            `Height     : ${user?.height ? user.height + ' cm' : '—'}`,
            `Weight     : ${user?.weight ? user.weight + ' kg' : '—'}`,
            '',
            '── ALLERGIES ────────────────────────────────────',
            user?.allergies ? user.allergies : 'No known allergies',
            '',
            '── MEDICAL CONDITIONS ───────────────────────────',
            user?.conditions ? user.conditions : 'No known conditions',
            '',
            '── ORGAN DONOR STATUS ───────────────────────────',
            organDonor ? 'Registered Organ Donor' : 'Not registered',
            '',
            '─────────────────────────────────────────────────',
            'This report is generated by Swasthya Mitra AI Health Platform.',
            'For medical emergencies call 112.',
        ].join('\n');

        const blob = new Blob([lines], { type: 'text/plain' });
        const url  = URL.createObjectURL(blob);
        const a    = document.createElement('a');
        a.href     = url;
        a.download = `HealthReport_${(user?.name || 'User').replace(/\s+/g, '_')}.txt`;
        a.click();
        URL.revokeObjectURL(url);
    };

    /* ── Photo upload ── */
    const handlePhotoChange = (e) => {
        const file = e.target.files[0];
        if (!file) return;
        const reader = new FileReader();
        reader.onload = async (ev) => {
            const dataUrl = ev.target.result;
            setPhotoSrc(dataUrl);
            // Persist photo in auth context / localStorage
            await updateProfile(user?.email, { photoUrl: dataUrl });
        };
        reader.readAsDataURL(file);
    };

    /* ════════════════════ OVERVIEW VIEW ════════════════════ */
    const OverviewView = () => (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            {/* ── Left (2/3) ── */}
            <div className="lg:col-span-2 space-y-6">
                {/* Profile Card */}
                <div className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 p-8 shadow-sm">
                    <div className="flex flex-wrap justify-between items-start gap-4 mb-8">
                        <div className="flex items-center gap-5">
                            {/* Avatar */}
                            <div className="size-20 rounded-2xl overflow-hidden border-2 border-slate-200 shadow-inner flex items-center justify-center bg-blue-600 text-white text-2xl font-black shrink-0">
                                {photoSrc ? (
                                    <img src={photoSrc} alt="Avatar" className="w-full h-full object-cover" />
                                ) : initials}
                            </div>
                            <div>
                                <div className="flex items-center gap-2 flex-wrap">
                                    <h2 className="text-2xl font-black text-slate-900 dark:text-white tracking-tight">{user?.name || 'User'}</h2>
                                    <span className="px-2 py-0.5 bg-blue-100 text-blue-700 font-bold text-[10px] rounded-full uppercase tracking-wider">Pro Member</span>
                                </div>
                                <div className="flex items-center gap-3 mt-1 text-xs font-bold text-slate-500 flex-wrap">
                                    <span className="flex items-center gap-1 text-emerald-600">
                                        <span className="material-symbols-outlined text-[14px]">verified</span> Verified Patient
                                    </span>
                                    <span>•</span>
                                    <span className="flex items-center gap-1 text-indigo-600">
                                        <span className="material-symbols-outlined text-[14px]">psychology</span> AI Health Enabled
                                    </span>
                                </div>
                                <p className="text-xs text-slate-500 mt-1.5 font-medium flex items-center gap-1">
                                    <span className="material-symbols-outlined text-sm">calendar_month</span>
                                    Member since {user?.createdAt ? new Date(user.createdAt).toLocaleDateString('en-US', { month: 'long', year: 'numeric' }) : 'Recently'}
                                </p>
                            </div>
                        </div>
                        <div className="flex gap-3 flex-wrap">
                            <button
                                onClick={handleDownload}
                                className="flex items-center gap-2 px-4 py-2 border border-slate-200 rounded-lg text-sm font-bold text-slate-700 hover:bg-slate-50 hover:border-slate-300 transition-all active:scale-[0.98]"
                            >
                                <span className="material-symbols-outlined text-[18px]">download</span>
                                Health Report
                            </button>
                            <button
                                onClick={() => setIsEditing(true)}
                                className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg text-sm font-bold hover:bg-blue-700 shadow-md shadow-blue-600/20 transition-all active:scale-[0.98]"
                            >
                                <span className="material-symbols-outlined text-[18px]">edit</span>
                                Edit Profile
                            </button>
                        </div>
                    </div>

                    {/* Personal Info Grid */}
                    <div>
                        <h3 className="text-sm font-bold flex items-center gap-2 text-slate-900 dark:text-slate-100 mb-4 pb-2 border-b border-slate-100 dark:border-slate-800">
                            <span className="material-symbols-outlined text-blue-600">person</span> Personal Information
                        </h3>
                        <div className="grid grid-cols-2 gap-y-5 gap-x-8">
                            <InfoRow label="Date of Birth"  value={formatDob(user?.dob)} />
                            <InfoRow label="Gender"         value={formatGender(user?.gender)} />
                            <InfoRow label="Email Address"  value={user?.email} />
                            <InfoRow label="Phone Number"   value={user?.phone} />
                        </div>
                    </div>
                </div>

                {/* Medical ID */}
                <div className="bg-white dark:bg-slate-900 rounded-2xl border border-red-100 dark:border-red-900/30 p-8 shadow-sm relative overflow-hidden">
                    <div className="absolute top-4 right-4">
                        <span className="px-3 py-1 bg-red-50 text-red-600 text-[10px] font-black uppercase tracking-widest rounded-full flex items-center gap-1">
                            <span className="material-symbols-outlined text-[12px]">emergency</span> Emergency Access
                        </span>
                    </div>
                    <h3 className="text-sm font-bold flex items-center gap-2 text-red-600 mb-6 pb-2 border-b border-red-50">
                        <span className="material-symbols-outlined">medical_information</span> Medical ID
                    </h3>
                    <div className="grid grid-cols-3 gap-6 mb-7">
                        <div>
                            <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-1">Blood Type</p>
                            <p className="text-3xl font-black text-slate-900 dark:text-white">{user?.bloodType || '—'}</p>
                        </div>
                        <div>
                            <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-1">Height</p>
                            <p className="text-3xl font-black text-slate-900 dark:text-white">{user?.height ? `${user.height}` : '—'}<span className="text-sm font-bold text-slate-400 ml-1">cm</span></p>
                        </div>
                        <div>
                            <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-1">Weight</p>
                            <p className="text-3xl font-black text-slate-900 dark:text-white">{user?.weight ? `${user.weight}` : '—'}<span className="text-sm font-bold text-slate-400 ml-1">kg</span></p>
                        </div>
                    </div>

                    {/* Allergies */}
                    <div className="mb-6">
                        <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-2">Known Allergies</p>
                        <div className="flex flex-wrap gap-2">
                            {getTags(user?.allergies).length > 0
                                ? getTags(user.allergies).map((a, i) => (
                                    <span key={i} className="px-3 py-1 bg-red-50 border border-red-100 text-red-700 font-bold text-xs rounded-lg">{a}</span>
                                ))
                                : <span className="px-3 py-1 bg-slate-50 border border-slate-200 text-slate-500 text-xs rounded-lg">No known allergies</span>
                            }
                        </div>
                    </div>

                    {/* Conditions */}
                    <div className="mb-7">
                        <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-2">Medical Conditions</p>
                        <div className="flex flex-wrap gap-2">
                            {getTags(user?.conditions).length > 0
                                ? getTags(user.conditions).map((c, i) => (
                                    <span key={i} className="px-3 py-1 bg-amber-50 border border-amber-100 text-amber-700 font-bold text-xs rounded-lg">{c}</span>
                                ))
                                : <span className="px-3 py-1 bg-slate-50 border border-slate-200 text-slate-500 text-xs rounded-lg">No known conditions</span>
                            }
                        </div>
                    </div>

                    {/* Emergency Contacts */}
                    <div>
                        <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mb-3">Emergency Contacts</p>
                        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                            {[
                                { initials: 'SJ', name: 'Sarah Johnson', relation: 'Spouse', phone: '+1 555-0987', tel: 'tel:+15550987' },
                                { initials: 'MJ', name: 'Mark Johnson',  relation: 'Brother', phone: '+1 555-1122', tel: 'tel:+15551122' },
                            ].map((c) => (
                                <div key={c.name} className="flex items-center p-4 border border-slate-100 dark:border-slate-800 rounded-xl hover:border-blue-200 transition-colors bg-slate-50 dark:bg-slate-800/50">
                                    <div className="w-10 h-10 rounded-full bg-blue-100 text-blue-700 font-black text-sm flex items-center justify-center mr-3 shrink-0">{c.initials}</div>
                                    <div className="flex-1 min-w-0">
                                        <p className="text-sm font-bold text-slate-900 dark:text-slate-100 truncate">{c.name}</p>
                                        <p className="text-[10px] font-semibold text-slate-500 uppercase truncate">{c.relation} • {c.phone}</p>
                                    </div>
                                    <a href={c.tel} className="text-blue-600 hover:text-blue-800 transition-colors ml-2" title={`Call ${c.name}`}>
                                        <span className="material-symbols-outlined text-[20px]">call</span>
                                    </a>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>
            </div>

            {/* ── Right (1/3) ── */}
            <div className="space-y-5">
                {/* Health Goals */}
                <div className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 p-6 shadow-sm">
                    <h3 className="text-sm font-bold flex items-center gap-2 text-slate-900 dark:text-slate-100 mb-5">
                        <span className="material-symbols-outlined text-blue-600">track_changes</span> Health Goals
                    </h3>
                    <div className="space-y-5">
                        <GoalBar label="Daily Steps"   current="8,432" target="10,000" unit="steps" pct={84} color="blue" />
                        <GoalBar label="Sleep Target"  current="7.2"   target="8.0"    unit="hrs"   pct={90} color="indigo" />
                        <GoalBar label="Target Weight" current="72"    target="70"     unit="kg"    pct={60} color="emerald" />
                    </div>
                    <button className="w-full mt-6 py-2.5 border border-slate-200 text-xs font-bold text-slate-600 rounded-xl hover:bg-slate-50 transition-colors">
                        View Detailed Progress
                    </button>
                </div>

                {/* Organ Donor Toggle */}
                <div className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 p-5 shadow-sm flex items-center justify-between">
                    <div>
                        <div className="flex items-center gap-2 text-sm font-bold text-slate-800 dark:text-slate-100">
                            <span className="material-symbols-outlined text-red-500">favorite</span>
                            Organ Donor
                        </div>
                        <p className="text-[10px] text-slate-400 mt-0.5">{organDonor ? 'Registered ✓' : 'Not registered'}</p>
                    </div>
                    <button
                        onClick={() => setOrganDonor((v) => !v)}
                        className={`w-12 h-6 rounded-full relative transition-colors duration-300 focus:outline-none focus:ring-2 focus:ring-offset-2 ${organDonor ? 'bg-blue-600 focus:ring-blue-500' : 'bg-slate-200 dark:bg-slate-700 focus:ring-slate-400'}`}
                        title="Toggle organ donor status"
                        aria-checked={organDonor}
                        role="switch"
                    >
                        <div className={`absolute top-1 w-4 h-4 bg-white rounded-full shadow transition-all duration-300 ${organDonor ? 'right-1' : 'left-1'}`} />
                    </button>
                </div>

                {/* Privacy Settings */}
                <div className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 p-5 shadow-sm">
                    <div className="flex gap-3 mb-4">
                        <div className="size-9 rounded-full bg-blue-50 text-blue-600 flex items-center justify-center shrink-0">
                            <span className="material-symbols-outlined text-[18px]">shield</span>
                        </div>
                        <div>
                            <h3 className="font-bold text-sm text-slate-900 dark:text-slate-100 mb-0.5">Privacy Settings</h3>
                            <p className="text-xs text-slate-500">You have full control over your health data.</p>
                        </div>
                    </div>
                    <div className="space-y-2 mb-4 text-xs">
                        <div className="flex justify-between border-b border-slate-50 dark:border-slate-800 pb-2">
                            <span className="font-semibold text-slate-500">Profile Visibility</span>
                            <span className="font-bold text-blue-600">Providers Only</span>
                        </div>
                        <div className="flex justify-between">
                            <span className="font-semibold text-slate-500">Data Sharing</span>
                            <span className="font-bold text-emerald-600 flex items-center gap-1">
                                <span className="material-symbols-outlined text-[12px]">lock</span> AES-256
                            </span>
                        </div>
                    </div>
                    <button className="w-full text-xs font-bold text-blue-600 uppercase tracking-widest hover:underline py-2">
                        Manage Permissions
                    </button>
                </div>

                {/* Insurance */}
                <div className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 p-5 shadow-sm">
                    <h3 className="text-sm font-bold flex items-center gap-2 text-slate-900 dark:text-slate-100 mb-4 pb-2 border-b border-slate-50 dark:border-slate-800">
                        <span className="material-symbols-outlined text-purple-600">health_and_safety</span> Insurance Plan
                    </h3>
                    <div className="flex items-center gap-3 mb-4">
                        <div className="w-12 h-8 rounded bg-blue-100 flex items-center justify-center text-blue-800 border border-blue-200">
                            <span className="material-symbols-outlined">assured_workload</span>
                        </div>
                        <div>
                            <p className="font-bold text-sm text-slate-900 dark:text-slate-100">BlueCross BlueShield</p>
                            <p className="text-[10px] font-bold text-slate-500 uppercase">ID #44820102 A • Platinum Plus</p>
                        </div>
                    </div>
                    <div className="flex justify-between items-center text-xs font-bold">
                        <span className="text-emerald-600 flex items-center gap-1">
                            <span className="material-symbols-outlined text-[14px]">check_circle</span> Active Coverage
                        </span>
                        <button className="text-blue-600 hover:underline">View Card</button>
                    </div>
                </div>
            </div>
        </div>
    );

    /* ════════════════════ EDIT VIEW ════════════════════ */
    const EditView = () => (
        <form onSubmit={handleSubmit} className="max-w-4xl mx-auto space-y-8">
            <div className="mb-6">
                <h1 className="text-2xl font-black text-slate-900 dark:text-slate-100 tracking-tight">Edit Profile &amp; Medical ID</h1>
                <p className="text-sm text-slate-500 mt-1">Manage your identity and critical health details.</p>
            </div>

            {/* Photo Upload */}
            <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-6 shadow-sm">
                <div className="flex items-center gap-5 mb-5">
                    <div className="relative">
                        <div className="w-20 h-20 rounded-2xl overflow-hidden border-2 border-slate-200 bg-blue-600 flex items-center justify-center text-white text-2xl font-black shrink-0">
                            {photoSrc ? <img src={photoSrc} alt="Avatar" className="w-full h-full object-cover" /> : initials}
                        </div>
                        <button
                            type="button"
                            onClick={() => photoInputRef.current?.click()}
                            className="absolute -bottom-2 -right-2 w-7 h-7 bg-blue-600 rounded-full text-white flex items-center justify-center border-2 border-white shadow-sm hover:bg-blue-700 transition-colors"
                            title="Upload photo"
                        >
                            <span className="material-symbols-outlined text-[14px]">add_a_photo</span>
                        </button>
                        <input
                            ref={photoInputRef}
                            type="file"
                            accept="image/*"
                            className="hidden"
                            onChange={handlePhotoChange}
                        />
                    </div>
                    <div>
                        <h2 className="text-xl font-bold text-slate-900 dark:text-slate-100">{user?.name || 'User'}</h2>
                        <p className="text-xs text-emerald-600 font-bold uppercase tracking-widest flex items-center gap-1 mt-1">
                            <span className="material-symbols-outlined text-[14px]">verified</span> Verified Identity
                        </p>
                    </div>
                </div>
                <button
                    type="button"
                    onClick={() => photoInputRef.current?.click()}
                    className="w-full bg-slate-50 dark:bg-slate-800 hover:bg-slate-100 dark:hover:bg-slate-700 border border-slate-200 dark:border-slate-700 text-sm font-bold text-slate-700 dark:text-slate-300 py-3 rounded-xl transition-colors flex items-center justify-center gap-2"
                >
                    <span className="material-symbols-outlined text-[18px]">upload</span> Upload New Photo
                </button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                {/* Left column */}
                <div className="space-y-8">
                    {/* Personal Info */}
                    <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-6 shadow-sm">
                        <h3 className="text-sm font-bold flex items-center gap-2 text-slate-900 dark:text-slate-100 mb-5 pb-2 border-b border-slate-100 dark:border-slate-800">
                            <span className="material-symbols-outlined text-blue-600">person</span> Personal Information
                        </h3>
                        <div className="space-y-4">
                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-[10px] font-bold uppercase tracking-widest text-slate-500 mb-1">Full Name</label>
                                    <input type="text" name="name" defaultValue={user?.name || ''} className="w-full px-3 py-2.5 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg text-sm font-semibold focus:ring-2 focus:ring-blue-500/20 focus:border-blue-400 outline-none transition" />
                                </div>
                                <div>
                                    <label className="block text-[10px] font-bold uppercase tracking-widest text-slate-500 mb-1">Phone Number</label>
                                    <input type="tel" name="phone" defaultValue={user?.phone || ''} className="w-full px-3 py-2.5 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg text-sm font-semibold focus:ring-2 focus:ring-blue-500/20 focus:border-blue-400 outline-none transition" />
                                </div>
                            </div>
                            <div>
                                <label className="block text-[10px] font-bold uppercase tracking-widest text-slate-500 mb-1">Email Address</label>
                                <input type="email" readOnly defaultValue={user?.email || ''} className="w-full px-3 py-2.5 bg-slate-100 dark:bg-slate-700/50 border border-slate-200 dark:border-slate-700 rounded-lg text-sm font-semibold text-slate-400 cursor-not-allowed outline-none" />
                            </div>
                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-[10px] font-bold uppercase tracking-widest text-slate-500 mb-1">Gender</label>
                                    <select name="gender" defaultValue={user?.gender || ''} className="w-full px-3 py-2.5 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg text-sm font-semibold focus:ring-2 focus:ring-blue-500/20 focus:border-blue-400 outline-none transition">
                                        <option value="">Select</option>
                                        <option value="male">Male</option>
                                        <option value="female">Female</option>
                                        <option value="non-binary">Non-binary</option>
                                        <option value="prefer-not-to-say">Prefer not to say</option>
                                    </select>
                                </div>
                                <div>
                                    <label className="block text-[10px] font-bold uppercase tracking-widest text-slate-500 mb-1">Date of Birth</label>
                                    <input type="date" name="dob" defaultValue={user?.dob || ''} className="w-full px-3 py-2.5 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg text-sm font-semibold focus:ring-2 focus:ring-blue-500/20 focus:border-blue-400 outline-none transition" />
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Medical ID */}
                    <div className="bg-white dark:bg-slate-900 border border-red-100 dark:border-red-900/30 rounded-2xl p-6 shadow-sm">
                        <h3 className="text-sm font-bold flex items-center gap-2 text-red-600 mb-5 pb-2 border-b border-red-50 dark:border-red-900/20">
                            <span className="material-symbols-outlined">medical_information</span> Medical ID
                        </h3>
                        <div className="space-y-4">
                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-[10px] font-bold uppercase tracking-widest text-slate-500 mb-1">Blood Type</label>
                                    <select name="bloodType" defaultValue={user?.bloodType || ''} className="w-full px-3 py-2.5 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg text-sm font-semibold focus:ring-2 focus:ring-red-500/20 focus:border-red-400 outline-none transition">
                                        <option value="">Select</option>
                                        {['A+','A-','B+','B-','AB+','AB-','O+','O-'].map(t => <option key={t}>{t}</option>)}
                                    </select>
                                </div>
                                <div>
                                    <label className="block text-[10px] font-bold uppercase tracking-widest text-slate-500 mb-1">Height (cm)</label>
                                    <input type="number" name="height" defaultValue={user?.height || ''} className="w-full px-3 py-2.5 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg text-sm font-semibold focus:ring-2 focus:ring-red-500/20 focus:border-red-400 outline-none transition" />
                                </div>
                            </div>
                            <div>
                                <label className="block text-[10px] font-bold uppercase tracking-widest text-slate-500 mb-1">Weight (kg)</label>
                                <input type="number" name="weight" defaultValue={user?.weight || ''} className="w-full px-3 py-2.5 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg text-sm font-semibold focus:ring-2 focus:ring-red-500/20 focus:border-red-400 outline-none transition" />
                            </div>
                            <div>
                                <label className="block text-[10px] font-bold uppercase tracking-widest text-slate-500 mb-1">Known Allergies</label>
                                <textarea name="allergies" rows="2" defaultValue={user?.allergies || ''} placeholder="e.g. Penicillin, Peanuts" className="w-full px-3 py-2.5 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg text-sm font-semibold focus:ring-2 focus:ring-red-500/20 focus:border-red-400 outline-none transition resize-none" />
                            </div>
                            <div>
                                <label className="block text-[10px] font-bold uppercase tracking-widest text-slate-500 mb-1">Chronic Conditions</label>
                                <textarea name="conditions" rows="3" defaultValue={user?.conditions || ''} placeholder="e.g. Type 2 Diabetes, Mild Asthma" className="w-full px-3 py-2.5 bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg text-sm font-semibold focus:ring-2 focus:ring-red-500/20 focus:border-red-400 outline-none transition resize-none" />
                            </div>
                        </div>
                    </div>
                </div>

                {/* Right column */}
                <div className="space-y-8">
                    {/* Emergency Contact */}
                    <div className="bg-red-50/50 dark:bg-red-950/10 border border-red-100 dark:border-red-900/30 rounded-2xl p-6 shadow-sm">
                        <h3 className="text-sm font-bold flex items-center gap-2 text-red-600 mb-5 pb-2 border-b border-red-100 dark:border-red-900/20">
                            <span className="material-symbols-outlined">emergency</span> Emergency Contact
                        </h3>
                        <div className="space-y-4">
                            <div>
                                <label className="block text-[10px] font-bold uppercase tracking-widest text-red-700 dark:text-red-400 mb-1">Contact Name</label>
                                <input type="text" defaultValue="Sarah Johnson" className="w-full px-3 py-2.5 bg-white dark:bg-slate-900 border border-red-100 dark:border-red-900/30 rounded-lg text-sm font-semibold focus:ring-2 focus:ring-red-500/20 focus:border-red-400 outline-none transition" />
                            </div>
                            <div>
                                <label className="block text-[10px] font-bold uppercase tracking-widest text-red-700 dark:text-red-400 mb-1">Relationship</label>
                                <input type="text" defaultValue="Spouse" className="w-full px-3 py-2.5 bg-white dark:bg-slate-900 border border-red-100 dark:border-red-900/30 rounded-lg text-sm font-semibold focus:ring-2 focus:ring-red-500/20 focus:border-red-400 outline-none transition" />
                            </div>
                            <div>
                                <label className="block text-[10px] font-bold uppercase tracking-widest text-red-700 dark:text-red-400 mb-1">Phone Number</label>
                                <input type="tel" defaultValue="+1 (555) 987-6543" className="w-full px-3 py-2.5 bg-white dark:bg-slate-900 border border-red-100 dark:border-red-900/30 rounded-lg text-sm font-semibold focus:ring-2 focus:ring-red-500/20 focus:border-red-400 outline-none transition" />
                            </div>
                            <button type="button" className="text-[10px] font-bold text-blue-600 uppercase tracking-widest hover:underline flex items-center gap-1 mt-1">
                                <span className="material-symbols-outlined text-[14px]">add_circle</span> Add Second Contact
                            </button>
                        </div>
                    </div>

                    {/* Organ Donor toggle */}
                    <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-5 shadow-sm flex items-center justify-between">
                        <div className="flex items-center gap-2 text-sm font-bold text-slate-800 dark:text-slate-100">
                            <span className="material-symbols-outlined text-red-500">favorite</span>
                            Organ Donor
                            <span className="text-[10px] font-medium text-slate-400">{organDonor ? '(Registered)' : '(Not registered)'}</span>
                        </div>
                        <button
                            type="button"
                            onClick={() => setOrganDonor((v) => !v)}
                            className={`w-12 h-6 rounded-full relative transition-colors duration-300 focus:outline-none focus:ring-2 focus:ring-offset-2 ${organDonor ? 'bg-blue-600 focus:ring-blue-500' : 'bg-slate-200 dark:bg-slate-700 focus:ring-slate-400'}`}
                            role="switch" aria-checked={organDonor}
                        >
                            <div className={`absolute top-1 w-4 h-4 bg-white rounded-full shadow transition-all duration-300 ${organDonor ? 'right-1' : 'left-1'}`} />
                        </button>
                    </div>

                    {/* Privacy info box */}
                    <div className="bg-blue-50/50 dark:bg-blue-950/10 border border-blue-100 dark:border-blue-900/30 rounded-2xl p-5 shadow-sm">
                        <h3 className="text-sm font-bold flex items-center gap-2 text-blue-700 dark:text-blue-400 mb-2">
                            <span className="material-symbols-outlined text-[18px]">lock</span> Privacy &amp; HIPAA
                        </h3>
                        <p className="text-xs text-slate-500 leading-relaxed mb-2">
                            Your medical data is encrypted and only accessible to authorized healthcare providers during emergency events.
                        </p>
                        <button type="button" className="text-[10px] font-bold text-blue-600 uppercase tracking-widest hover:underline">Learn more</button>
                    </div>
                </div>
            </div>

            {/* Actions */}
            <div className="flex items-center justify-end gap-4 pt-6 border-t border-slate-200 dark:border-slate-800">
                <button
                    type="button"
                    onClick={() => setIsEditing(false)}
                    className="px-6 py-2.5 text-sm font-bold text-slate-500 hover:text-slate-800 dark:hover:text-slate-200 transition-colors"
                >
                    Cancel
                </button>
                <button
                    type="submit"
                    className="px-6 py-2.5 bg-blue-600 text-white text-sm font-bold rounded-xl shadow-lg shadow-blue-600/20 hover:bg-blue-700 transition-all flex items-center gap-2 active:scale-[0.98]"
                >
                    <span className="material-symbols-outlined text-[18px]">save</span> Save All Changes
                </button>
            </div>
        </form>
    );

    /* ─── render ─── */
    return (
        <AppLayout activeTab="records">
            {/* Save success toast */}
            {saveSuccess && (
                <div className="fixed top-6 right-6 z-50 flex items-center gap-3 bg-emerald-600 text-white px-5 py-3.5 rounded-2xl shadow-xl shadow-emerald-600/30 animate-bounce-in">
                    <span className="material-symbols-outlined text-[20px]">check_circle</span>
                    <span className="font-bold text-sm">Profile saved successfully!</span>
                </div>
            )}

            {/* Page header */}
            <div className="mb-6">
                <h1 className="text-2xl font-black text-slate-900 dark:text-slate-100 tracking-tight">
                    {isEditing ? 'Edit Profile & Medical ID' : 'Health Records'}
                </h1>
                <p className="text-sm text-slate-500 mt-1 font-medium">
                    {isEditing ? 'Update your personal and medical information.' : 'Your complete medical profile and health records.'}
                </p>
            </div>

            {isEditing ? <EditView /> : <OverviewView />}
        </AppLayout>
    );
};

export default PatientProfileRecords;
